# -*- coding: utf-8 -*-
from fpdf import FPDF

pdf=FPDF()
#Adicionando página
pdf.add_page()
#Adicionando configurações de Fonte
pdf.set_font('Arial','B',16)
#Inserindo linhas cell by cell.
pdf.cell(0,10,'CONTRATO DE LOCAÇÃO RESIDENCIAL', 1,1 , 'C')

#Locador
pdf.set_font('Arial','I',8)
pdf.cell(33,5,'LOCADOR(A):',1,1 , 'L')
pdf.cell(0,5,'..................................., brasileiro, solteiro, comerciante,', 0,1 , 'J')
pdf.cell(0,5,'portador da cédula de identidade RG ....................../SSP.SP e inscrito no CPFMF sob nº ................', 0,1 , 'J')
#Locatario
pdf.cell(33,5,'LOCATÁRIO(A):',1,1 , 'L')
pdf.cell(0,5,'................................................, brasileiro, casado, autônomo,', 0,1 , 'J')
pdf.cell(0,5,', portador da cédula de identidade RG .................SSP/SP e inscrito no CPFMF sob nº ................... ', 0,1 , 'J')
pdf.ln(5)
#Objeto
pdf.set_font('Arial','B',8)
pdf.cell(0,5,'OBJETO:',1,1 , 'L')
pdf.set_font('Arial','',9)
pdf.cell(0,5,'A CASA SOB Nº ....., DA RUA ............................., ou A UNIDADE RESIDENCIAL SOB N ....., SITIO NA RUA', 0,1 ,'')
pdf.cell(0,5,' ............. N ...,,0,1,'')
pdf.ln(5)
#--
pdf.set_font('Arial','I',8)
pdf.cell(0,5,'Por este particular instrumento, as partes supraqualificadas resolvem, de comum acordo e de livre e espontânea',0,1,'L')
pdf.cell(0,5,' vontade, firmar um Contrato de Locação, tendo por objeto o imóvel declinado no preâmbulo, a reger-se pelas se',0,1,'L')
pdf.cell(0,5,'guintes cláusulas e condições',0,1,'L')
pdf.ln(1)
#Primeira
pdf.set_font('Arial','',8)
pdf.cell(33,5,'PRIMEIRA:',1,1 , 'L')
pdf.ln(1)
pdf.cell(0,5,'prazo da locação é de trinta (30) meses, iniciando-se no dia 00.....2003 e findando-se em 00.....2005,quando e',0,1, 'J')
pdf.cell(0,5,'ntão será considerada finda, independentemente de notificação judicial ou extrajudicial, obrigando-se o(a) LOC',0,1, 'J')
pdf.cell(0,5,'  (vide observação 01)', 0,1, 'J')
pdf.ln(1)
#Segunda
pdf.cell(33,5,'SEGUNDA:', 1,1, 'L')
pdf.ln(1)
pdf.cell(0,5,'O aluguel convencionado é de R$ ........ (....................... reais) mensais,diretamente à .............',0,1,'J')
pdf.cell(0,5,'(nome do(a) administrador(a)), estabelecido(a) na rua .........., ou a quem vier o(a) LOCADOR(A) a indicar,s',0,1,'J')
pdf.cell(0,5,'empre porém na cidade de .................. (a mesma do local de pagamento contratual). (vide observação 02)',0,1, 'J')
pdf.ln(1)
#Terceira
pdf.cell(33,5,'TERCEIRA:', 1,1, 'L')
pdf.ln(1)
pdf.cell(0,5,'O valor do locativo mensal será anualmente reajustado, segundo os índices do .......(escolher um índice prin', 0,1, 'J')
pdf.cell(0,5,'cipal)acumulados no período e, no caso de sua extinção, de forma alternativa e subsidiária, pelos do .......', 0,1 , 'J')
pdf.cell(0,5,'(declinar outros dois).', 0,1, 'J')
pdf.ln(1)
#Quarta
pdf.cell(33,5,'QUARTA:', 1,1, 'L')
pdf.ln(1)
pdf.cell(0,5,'A não observância do prazo estabelecido na cláusula segunda,implicará na incidência de multa diária de 1% so', 0,1 , 'J')
pdf.cell(0,5,'bre o valor, do aluguel até o limite de 20%, acrescido de juros de mora de ......... ao mês ou fração e atua', 0,1 , 'J')
pdf.cell(0,5,'lização monetária. (vide observação 03 e 04)', 0,1, 'J')
pdf.ln(1)
#Quinta
pdf.cell(33,5,'QUINTA:', 1,1, 'L')
pdf.ln(1)
pdf.cell(0,5,'Além do aluguel, obriga se o(a) LOCATÁRIO(A) a efetuar o pagamento dos seguintes encargos,:que poderão ser e',0,1,'J')
pdf.cell(0,5,'xigidos juntamente com o aluguel:', 0,1 , 'J')
pdf.cell(0,5,'a.	o imposto predial e territorial;',0,1,'J')
pdf.cell(0,5,'b.	o consumo de água e energia elétrica;',0,1,'J')
pdf.cell(0,5,'c. o prêmio de seguro contra incêndio, que deverá ser feito pelo valor venal do imóvel, nele figurando o(a) LOCADOR(A) como beneficiário(a);',0,1,'J')
pdf.cell(0,5,'d.	as taxas de condomínio, se houverem;',0,1,'J')
pdf.cell(0,5,'e.	os demais encargos e tributos que normalmente incidem ou venham a incidir sobre o imóvel. (vide observação 05) ',0,1,'J')
pdf.cell(0,5,'ÚNICO:	O não pagamento desses encargos nas épocas próprias, facultará ao(a) LOCADOR(A) a justa recusa ao recebimento dos alugueres,',0,1,'J')
pdf.cell(0,5,'sujeitando-se o(a) LOCATÁRIO(A) ao pagamento dos ônus decorrentes do inadimplemento,',0,1,'J')
pdf.cell(0,5,', previstos para cada débito, independentemente de eventual ação de despejo. ',0,1,'J')
pdf.ln(1)
#Sexta
pdf.cell(33,5,'SEXTA:', 1,1, 'L')
pdf.ln(1)
pdf.cell(0,5,'O imóvel objeto deste instrumento é locado exclusivamente para servir de residência ao(à) LOCATÁRIO(A) e sua',0,1,'J')
pdf.cell(0,5,' família, não podendo sua destinação ser alterada, ou acrescida de qualquer outra, sem prévia e expressa anu',0,1,'J')
pdf.cell(0,5,'ência do(a) LOCADOR(A). Fica vedado, outrossim, a sublocação, cessão ou transferência deste contrato, bem co',0,1,'J')
pdf.cell(0,5,'mo o empréstimo,parcial ou total do imóvel locado, que dependerão também, de prévia e expressa anuência do(a',0,1,'J')
pdf.cell(0,5,') LOCADOR(A).', 0,1,'J')
pdf.ln(1)
#Setima
pdf.cell(33,5,'SÉTIMA:', 1,1, 'L')
pdf.ln(1)
pdf.cell(0,5,'O imóvel objeto deste, foi ......(vide observação 06)...(1) - entregue ao(a) LOCATÁRIO(A) nas condições desc',0,1,'J')
pdf.cell(0,5,'ritas no “Termo de Vistoria” devidamente assinado pelas partes, integrando o presente,, obrigando-se a devol',0,1,'J')
pdf.cell(0,5,'vê-lo, uma vez finda a locação, nas mesmas condições em que o recebeu,razão pela qual, no momento da restitu',0,1,'J')
pdf.cell(0,5,'ição das chaves, proceder-se-á a uma nova vistoria...(2) - devidamente vistoriado pelo(a) LOCATÁRIO(A), que ',0,1,'J')
pdf.cell(0,5,'constatou encontrar-se em perfeitas condições de habitabilidade, com pintura nova, portas com fechaduras em ',0,1,'J')
pdf.cell(0,5,'funcionamento e munidas das correspondentes chaves,azulejos e porcelanas da cozinha e banheiro inteiros, abe',0,1,'J')
pdf.cell(0,5,'rturas com ferragens em condições e vidros inteiros, instalação elétrica e hidráulica em condições, obrigand',0,1,'J')
pdf.cell(0,5,'o-se a devolvê-lo, uma vez finda a locação, nas mesmas condições em que o recebeu, , razão pela qual, no mom',0,1,'J')
pdf.cell(0,5,'ento da restituição das chaves, proceder-se-á a uma nova vistoria.', 0,1 , '')
pdf.cell(0,5,'ÚNICO: Constatadas eventuais irregularidades e a necessidade de reparos no imóvel em decorrência de uso inde',0,1,'J')
pdf.cell(0,5,'vido,fará o(a) LOCADOR(A) apresentar de imediato ao(à) LOCATÁRIO(A), um orçamento prévio assinado por profis',0,1,'J')
pdf.cell(0,5,'sional do ramo, sendo-lhe facultado pagar o valor nele declinado, liberando-se assim de eventuais ônus em ra',0,1,'J')
pdf.cell(0,5,'zão de demora e/ou imperfeições nos serviços. Caso contrário, poderá contratar por sua própria conta e risco',0,1,'J')
pdf.cell(0,5,' mão-de-obra especializada, arcando nessa condição com os riscos de eventuais imperfeições dos serviços e pe',0,1,'J')
pdf.cell(0,5,'lo pagamento do aluguel dos dias despendidos para a sua execução,cessando a locação unicamente com o “Termo ',0,1,'J')
pdf.cell(0,5,'de Entrega de Chaves e Vistoria”, firmado pelo(a) LOCADOR(A) ou seu(sua) administrador(a).',0,1,'J')
pdf.ln(1)
#Oitava
pdf.cell(33,5,'OITAVA:', 1,1, 'L')
pdf.ln(1)
pdf.cell(0,5,'Obriga-se o(a) LOCATÁRIO(A) a manter o imóvel sempre limpo e bem cuidado na vigência da locação,, correndo p',0,1,'J')
pdf.cell(0,5,'or sua conta e risco, não só os pequenos reparos tendentes a sua conservação, mas também as multas a que der',0,1,'J')
pdf.cell(0,5,' causa, por inobservância de quaisquer leis, decretos e/ou regulamentos.', 0,1 , 'J')
pdf.ln(1)
#Nona
pdf.cell(33,5,'NONA:', 1,1, 'L')
pdf.ln(1)
pdf.cell(0,5,'O(A) LOCATÁRIO(A) não poderá fazer no imóvel ou em suas dependências, quaisquer obras ou benfeitorias, sem p',0,1,'J')
pdf.cell(0,5,'révia e expressa anuência do(a) LOCADOR(A),não lhe cabendo direito de retenção, por aquelas que, mesmo neces',0,1,'J')
pdf.cell(0,5,'sárias ou consentidas, venham a ser realizadas.', 0,1 , 'J')
pdf.cell(0,5,'§ ÚNICO: Caso não convenha ao(à) LOCADOR(A) a permanência de quaisquer obras ou benfeitorias realizadas pelo',0,1,'J')
pdf.cell(0,5,'(a) LOCATÁRIO(A), mesmo necessárias ou consentidas, deverá este(a), uma vez finda a locação, removê-las às s',0,1,'J')
pdf.cell(0,5,'uas expensas, de modo a devolver o imóvel nas mesmas condições em que o recebeu. ', 0,1 , 'J')
pdf.ln(1)
#Decima
pdf.cell(33,5,'DÉCIMA:', 1,1, 'L')
pdf.ln(1)
pdf.cell(0,5,'Obriga-se desde já o(a) LOCATÁRIO(A), a respeitar os regulamentos e as leis vigentes,bem como o direito de v',0,1,'J')
pdf.cell(0,5,'izinhança, evitando a prática de quaisquer atos que possam perturbar a tranqüilidade ou ameaçar a saúde públ',0,1,'J')
pdf.cell(0,5,'ica.',0,1,'J')
pdf.ln(1)
#Decima-Primeira
pdf.cell(33,5,'DÉCIMA-PRIMEIRA:', 1,1, 'L')
pdf.ln(1)
pdf.cell(0,5,'Como fiadores e principais pagadores de todas as obrigações que incumbem ao(a) LOCATÁRIO(A),por força de lei',0,1,'J')
pdf.cell(0,5,' ou do presente contrato e até a efetiva desocupação do imóvel, nas condições previstas pela cláusula sétima',0,1,'J')
pdf.cell(0,5,' deste, assinam ..................... e sua mulher ........................., ele servidor público, portador',0,1,'J')
pdf.cell(0,5,' da cédula de identidade RG ......./SSP.SP e inscrito no CPFMF sob nº .................. e ela do lar, porta',0,1,'J')
pdf.cell(0,5,'dora da cédula de identidade RG ................./SSP.SP e inscrita no CPFMF sob nº .......................,',0,1,'J')
pdf.cell(0,5,' ambos brasileiros, casados pelo regime da comunhão universal de bens, antes da vigência da Lei 6.515/77, re',0,1,'J')
pdf.cell(0,5,'sidentes e domiciliados na rua ................................ nº ....., na cidade de ..................,qu',0,1,'J')
pdf.cell(0,5,'e neste ato renunciam ao benefício de ordem, estabelecido pelo artigo 827,do Código Civil.(videObservação07)',0,1,'J')
pdf.cell(0,5,' ÚNICO: Fica convencionado que os fiadores supramencionados não se eximirão da obrigação ora assumida, caso ',0,1,'J')
pdf.cell(0,5,'a locação, seja por força de lei, de contrato ou por ajuste feito entre LOCADOR(A) e LOCATÁRIO(A), se prorro',0,1,'J')
pdf.cell(0,5,'gue por prazo superior ao convencionado. (vide observação 08)', 0,1, '')
pdf.ln(1)
#Decima-Segunda
pdf.cell(33,5,'DÉCIMA-SEGUNDA:', 1,1, 'L')
pdf.ln(1)
pdf.cell(0,5,'	Qualquer tolerância ou concessão, com o fito de resolver extrajudicialmente questão legal ou contratual,nã',0,1,'J')
pdf.cell(0,5,'o se constituirá em precedente invocável pelo(a) LOCATÁRIO(A) e nem modificará quaisquer das condições estab',0,1,'J')
pdf.cell(0,5,'elecidas neste instrumento. ',0,1,'J')
pdf.ln(1)
#Decima-Terceira
pdf.cell(33,5,'DÉCIMA-TERCEIRA:', 1,1, 'L')
pdf.ln(1)
pdf.cell(0,5,'Em caso de morte, exoneração, falência ou insolvência de quaisquer dos fiadores, obriga-se o(a) LOCATÁRIO(A)',0,1,'J')
pdf.cell(0,5,',num prazo de quinze (15) dias, contados da verificação do fato, a apresentar substituto idôneo ao(à) LOCADO',0,1,'J')
pdf.cell(0,5,'R(A), à juízo deste(a) (apenas se a garantia for através de fiança). ', 0,1, 'J')
pdf.ln(1)
#Decima-Quarta
pdf.cell(33,5,'DÉCIMA-QUARTA:', 1,1, 'L')
pdf.ln(1)
pdf.cell(0,5,'Obriga-se o(a) LOCATÁRIO(A) a efetuar a ligação de energia elétrica em seu nome, providenciando no seu desli',0,1,'J')
pdf.cell(0,5,'gamento,por ocasião da devolução do imóvel, quando então deverá apresentar as últimas contas de seu consumo.',0,1,'J')
pdf.cell(0,5,' (vide observação 09)',0,1,'J')
pdf.ln(1)
#Decima-Quinta
pdf.cell(33,5,'DÉCIMA-QUINTA:', 1,1, 'L')
pdf.ln(1)
pdf.cell(0,5,'A falta de cumprimento de qualquer cláusula ou condição deste instrumento, implicará na sua imediata rescisã',0,1,'J')
pdf.cell(0,5,'o,ficando a parte infratora, sujeita ao pagamento de uma multa, equivalente a três meses de aluguel, pelo va',0,1,'J')
pdf.cell(0,5,'lor vigente à época da infração, além de perdas e danos.  (vide observação 10)', 0,1, 'J')
pdf.ln(1)
#Decima-Sexta
pdf.cell(33,5,'DÉCIMA-SEXTA:', 1,1, 'L')
pdf.ln(1)
pdf.cell(0,5,'Sempre que as partes forem obrigadas a se valer de medidas judiciais para a defesa de direitos e obrigações ',0,1,'J')
pdf.cell(0,5,'decorrentes deste instrumento, o valor devido a título de honorários, será de 20% (vinte por cento) sobre o ',0,1,'J')
pdf.cell(0,5,'valor da causa, elegendo, desde já, o foro da cidade de ....... (o mesmo da situação do imóvel), para a solu',0,1,'J')
pdf.cell(0,5,'ção das questões dele emergentes.',0,1,'J')
pdf.ln(1)
#Inicio-Obs
pdf.set_font('Arial','I',8)
pdf.cell(0,10,'E por estarem assim justas e contratadas, assinam o presente, em três (03) vias, de igual teor e forma, na ',0,1,'J')
pdf.cell(0,10,'presença das testemunhas retro, para que surta seus legais e jurídicos efeitos, obrigando-se por si, seus h',0,1,'J')
pdf.cell(0,10,'erdeiros e/ou sucessores,ao fiel cumprimento de todas as suas cláusulas e condições.', 0,1 , 'J')
pdf.ln(10)
#Locadores
pdf.set_font('Arial', '', 8)
pdf.cell(0,5,'_____ , _____ , _________', 0,1 , 'C')
pdf.ln(10)
pdf.cell(0,5,'__________________________________________________',0,1,'J')
pdf.cell(0,5,'                    Locador(a)                   ', 0,1, 'J')
pdf.cell(0,5,'__________________________________________________', 0,1, 'J')
pdf.cell(0,5,'                    Locatário(a)                  ',0,1, 'J')
pdf.cell(0,5,'__________________________________________________', 0,1, 'J')
pdf.cell(0,5,'                        Fiador                   ', 0,1, 'J')
pdf.cell(0,5,'__________________________________________________', 0,1, 'J')
pdf.cell(0,5,'                        Fiadora                    ', 0,1 , 'J')
pdf.cell(0,5,'TESTEMUNHAS',0,1,'')
pdf.cell(0,5,'__________________________________________________', 0,1, 'J')
pdf.cell(0,5,'__________________________________________________', 0,1, 'J')
#Observacoes
pdf.set_font('Arial', 'B' , 12)
pdf.cell(0,5,'OBSERVAÇÕES IMPORTANTES',1,1, 'C')
pdf.cell(0,5,'INTEGRANTES DA MINUTA DE CONTRATO DE LOCAÇÃO RESIDENCIAL ',1,1,'C')
pdf.ln(1)
#Observacao01
pdf.set_font('Arial', 'I', 8)
pdf.cell(0,5,'Observação 01: Muito embora o artigo 565, do novo Código Civil não tenha mais estabelecido o prazo mínimo d',0,1,'J')
pdf.cell(0,5,'e 30 meses previsto na legislação locatícia, ainda não existe manifestação de nossos Tribunais sobre eventu',0,1,'J')
pdf.cell(0,5,'al revogação dessa regra. Como pela legislação locatícia, o prazo inferior a 30 meses implicava na prorroga',0,1,'J')
pdf.cell(0,5,'ção automática do contrato e exigia para a retomada circunstâncias especiais ou o decurso de 5 anos, o acon',0,1,'J')
pdf.cell(0,5,'selhável é ainda se utilizar esse prazo (30 meses). ',0,1,'J')
pdf.ln(1)
#Observacao02
pdf.cell(0,5,'Observação 02: Normalmente, no primeiro mês de locação ocorre a cobrança do aluguel “pro-rata”,seja, os dia',0,1,'J')
pdf.cell(0,5,'s ocupados decorridos desde o início da locação até o final do mês.Somente a partir do segundo mês é que é ',0,1,'J')
pdf.cell(0,5,'feita a cobrança do valor locatício integral. ',0,1,'J')
pdf.ln(1)
#Observacao03
pdf.cell(0,5,'Observação 03: Muitos administradores criam aquilo que se chama de “abono de pontualidade”, reduzindo o val',0,1,'J')
pdf.cell(0,5,'or do aluguel em determinado percentual, caso seja pago até a data do vencimento. Essa prática é reconhecid',0,1,'J')
pdf.cell(0,5,'a pelos Tribunais como mora disfarçada e muitos a consideram ilegal, não podendo jamais ser cumulada com mu',0,1,'J')
pdf.cell(0,5,'lta de mora. O mais salutar é convencionar o valor real do aluguel e fazer incidir uma mora diária no caso ',0,1,'J')
pdf.cell(0,5,'de inadimplemento, até o limite de 20% (máximo permitido pelos Tribunais). Ao contrário da multa integral d',0,1,'J')
pdf.cell(0,5,'esde o primeiro dia de atraso, a multa escalonada estimula o locatário a resgatar o débito, mesmo após o pr',0,1,'J')
pdf.cell(0,5,'imeiro dia de vencimento,  pois ela é progressiva até o vigésimo dia de atraso.',0,1,'J')

pdf.ln(1)
#Observacao04
pdf.cell(0,5,'Observação 04: O artigo 406, do novo Código Civil, aparentemente teria revogado de forma expressa o artigo',0,1,'J')
pdf.cell(0,5,' 1, do Decreto 22.626/33, que estabelecia vedação de juros superiores a 1% ao mês. Pelo citado artigo, el',0,1,'J')
pdf.cell(0,5,'es poderiam ser convencionados acima desse limite. Como a lei não estabelece o limite máximo, a idéia lógi',0,1,'J')
pdf.cell(0,5,'ca seria a de que o limite máximo ficaria ao arbítrio das partes. Só que esse entendimento, com toda certe',0,1,'J')
pdf.cell(0,5,'za, será objeto de questionamento pelos Tribunais, que no devido tempo, deverão estabelecer os percentuais',0,1,'J')
pdf.cell(0,5,'máximos a serem aplicados. A única certeza, é de que o limite permitido é o das taxas da Fazenda Nacional ',0,1,'J')
pdf.cell(0,5,'(taxa SELIC). Por isso, recomenda-se prudência e coerência.',0,1,'J')
pdf.ln(1)
#Observacao05
pdf.cell(0,5,'Observação 05: Nunca entregar para o(a) locatário(a) o carnê do IPTU e nunca permitir que as taxas condomi',0,1,'J')
pdf.cell(0,5,'niais sejam remetidas diretamente ao mesmo.Sempre cuidar para que esses pagamentos sejam realizados pelo(a',0,1,'J')
pdf.cell(0,5,') administrador(a),pois é dele a responsabilidade pelo inadimplemento. Todos esses valores são normalmente',0,1,'J')
pdf.cell(0,5,'cobrados juntamente com o aluguel.Não se descuidar da contratação de seguro-incêndio,pois se algum sinistr',0,1,'J')
pdf.cell(0,5,'o ocorrer no imóvel e este não tiver seguro, o(a) administrador(a) será responsável pelo prejuízo.',0,1,'J')
pdf.ln(1)
#Observacao06
pdf.cell(0,5,'Observação 06:  Duas opções são informadas. A mais correta é a primeira, com a realização de vistoria, atr',0,1,'J')
pdf.cell(0,5,'avés de termo,sendo uma dias vias entregue ao locatário, com o seguinte texto, transcrito em destaque,após',0,1,'J')
pdf.cell(0,5,'os dados da vistoria e no canto direito do formulário: ',0,1,'J')
pdf.set_font('Arial','', 7)
pdf.cell(0,5,'“Recebi a primeira via deste, ciente de que disponho do prazo de quarenta e oito (48) horas para encaminha',0,1,'J')
pdf.cell(0,5,'r ao(à) administrador(a) reclamação escrita de qualquer anormalidade encontrada no imóvel, ou de condições',0,1,'J')
pdf.cell(0,5,'que estejam em desacordo com os termos da presente vistoria, ciente também de que meu silêncio, fará presu',0,1,'J')
pdf.cell(0,5,'mir o aceite das condições aqui mencionadas.',0,1,'J')
pdf.cell(0,5,'.............., .... de ................... de ...........',0,1,'J')
pdf.cell(0,5,'Locatário',0,1,'C')
pdf.ln(1)
#Observacao07
pdf.set_font('Arial', 'I', 8)
pdf.cell(0,5,'Observação 07: (a) A garantia locatícia é um dos maiores problemas do contrato. Existem três tipos: caução',0,1,'J')
pdf.cell(0,5,', fiança e seguro-fiança, só podendo ser exigida uma delas. A caução, normalmente em dinheiro e equivalent',0,1,'J')
pdf.cell(0,5,'e a três meses de aluguel, não deve ser entregue ao(a) locador(a), mas sim depositada em conta poupança de',0,1,'J')
pdf.cell(0,5,'instituição oficial, aberta em nome do(a) administrador(a), onde deverá permanecer até a recisão do contra',0,1,'J')
pdf.cell(0,5,'to, oportunidade em que deverá ser devolvida ao(à) locatário(a), com os acréscimos percebidos. Como débito',0,1,'J')
pdf.cell(0,5,'s de inadimplência e reparos costumam ser muito superiores a três meses de aluguel, não se recomenda esse ',0,1,'J')
pdf.cell(0,5,'tipo de garantia. (b) A caução imobiliária (que deve ser objeto de  averbação à margem da matrícula do imó',0,1,'J')
pdf.cell(0,5,'vel, a vista de escritura pública específica de caução ou do próprio contrato elaborado com as formalidade',0,1,'J')
pdf.cell(0,5,'s legais) pode ser utilizada com segurança, pois o imóvel permanecerá como garantia até o final do prazo a',0,1,'J')
pdf.cell(0,5,'justado e como se encontra registrada no Ofício Predial, mesmo no caso de sua alienação a terceiros, perma',0,1,'J')
pdf.cell(0,5,'necerá intacta. (c) O seguro-fiança é boa garantia. Entretanto, como depende do pagamento do prêmio, o(a) ',0,1,'J')
pdf.cell(0,5,'administrador(a) corre o risco de ser obrigado(a) a arcar com o seu pagamento, caso o(a) locatário(a) não ',0,1,'J')
pdf.cell(0,5,'venha a fazê-lo, sob pena de ser responsabilizado pelos prejuízos. Deve, pois, o administrador estar atent',0,1,'J')
pdf.cell(0,5,'o para o pagamento pontual do prêmio. (d) A fiança envolve valores que asseguram indenização integral no c',0,1,'J')
pdf.cell(0,5,'aso de inadimplemento e ressarcimento dos reparos. Cuidados se fazem necessários na completa busca dos dad',0,1,'J')
pdf.cell(0,5,'os cadastrais e antecedentes dos fiadores, que necessariamente deverão residir e ser proprietários exclusi',0,1,'J')
pdf.cell(0,5,'vos de, pelo menos um imóvel além daquele onde residem (precavendo-se assim dos efeitos da decisão do STF ',0,1,'J')
pdf.cell(0,5,'nos autos do RE 352940, ue entendeu ser impenhorável o imóvel onde reside o fiador), no mesmo local de sit',0,1,'J')
pdf.cell(0,5,'uação do imóvel locado, para evitar dificuldades processuais no caso de execução, cuidando para que não se',0,1,'J')
pdf.cell(0,5,'ja um terreno sem valor comercial.',0,1,'J')
pdf.ln(1)
#Observacao08
pdf.cell(0,5,'Observação 08: A fiança não permite interpretação extensiva. Desta forma, por exemplo, reajustes de alugu',0,1,'J')
pdf.cell(0,5,'eres acima dos índices pactuados, não terão validade para os fiadores, se não anuírem de forma expressa c',0,1,'J')
pdf.cell(0,5,'om esses reajustes. Por isso, sempre que houver qualquer alteração não prevista no contrato, tomar a prov',0,1,'J')
pdf.cell(0,5,'idência de exigir a concordância dos fiadores. Nos termos do atual inciso X, do artigo 40, da Lei do Inqu',0,1,'J')
pdf.cell(0,5,'ilinato alterada, uma vez prorrogado o contrato por prazo indeterminado, o fiador poderá se desonerar do ',0,1,'J')
pdf.cell(0,5,'encargo, por via de notificação ao locador, permanecendo responsável por todos os efeitos, pelo prazo de ',0,1,'J')
pdf.cell(0,5,'120 dias, cabendo ao locador notificar o locatário para apresentar novo fiador no prazo de 30 dias, sob p',0,1,'J')
pdf.cell(0,5,'ena de despejo. ',0,1,'J')
pdf.ln(1)
#Observacao09
pdf.cell(0,5,'Observação 09: Cuidar para que a ligação de energia elétrica seja sempre realizada (ou transferida) para',0,1,'J')
pdf.cell(0,5,' o nome do locatário, a fim de que a eventual cobrança e a inclusão em cadastro de inadimplentes não sej',0,1,'J')
pdf.cell(0,5,'a feita em nome do(a) locador(a). ',0,1,'J')
pdf.ln(1)
#Observacao10
pdf.cell(0,5,'Observação 10: A multa indenizatória sempre será proporcional ao prazo restante do contrato. ',0,1,'J')
pdf.ln(1)
#ObservacaoFinal
pdf.set_font('Arial', 'B', 8)
pdf.cell(0,5,'OBSERVAÇÃO FINAL: A presente minuta é apenas uma sugestão, nela informadas as cláusulas básicas de um co',0,1,'J')
pdf.cell(0,5,'ntrato de locação residencial, às quais deverão ser adicionadas outras que vierem a ser necessárias, em ',0,1,'J')
pdf.cell(0,5,'face das características particulares de cada negócio. ',0,1,'J')

pdf.output('Locacao.pdf','F')
pdf=FPDF('P','mm','A4')
